//
//  MainInteractorTests.swift
//  GitHubAPP
//
//  Created by Murilo de Souza Lopes on 04/08/19.
//  Copyright (c) 2019 Murilo de Souza Lopes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import GitHubAPP
import XCTest

class MainInteractorTests: XCTestCase
{
}
