//
//  MainInteractorTests.swift
//  GitHubAPP
//
//  Created by Murilo de Souza Lopes on 04/08/19.
//  Copyright (c) 2019 Murilo de Souza Lopes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import GitHubAPP
import XCTest

class MainInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: MainInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupMainInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMainInteractor()
  {
    sut = MainInteractor()
  }
  
  // MARK: Test doubles
  
  class MainPresentationLogicSpy: MainPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: Main.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = MainPresentationLogicSpy()
    sut.presenter = spy
    let request = Main.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
