//
//  MainRouter.swift
//  
//
//  Created by Murilo de Souza Lopes on 02/08/19.
//  Copyright (c) 2019 Murilo de Souza Lopes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic {
    func routeToRepo()
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {
    
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?
    
    func routeToRepo() {
        let destinationVC = RepoViewController()
        var destinationDS = destinationVC.router?.dataStore
        passDataToRepo(source: dataStore!, destination: &destinationDS!)
        navigateToRepo(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToRepo(source: MainViewController, destination: RepoViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToRepo(source: MainDataStore, destination: inout RepoDataStore)
    {
        destination.item = source.item!
    }
}
