//
//  MainPresenter.swift
//  Clean Swift Template Project
//
//  Created by Murilo de Souza Lopes on 02/08/19.
//  Copyright (c) 2019 Murilo de Souza Lopes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
    func presentSomething(response: Main.Something.Response)
}

class MainPresenter: MainPresentationLogic
{
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Main.Something.Response)
    {
        let viewModel = Main.Something.ViewModel(item: response.item)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
